services:
  localstack:
    container_name: beauty-booking-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - SERVICES=s3,dynamodb,iam,lambda,sqs,sns,ec2,apigateway,ecs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # Prevent tmp directory issues
      - TMPDIR=/tmp/localstack_tmp
      # Avoid persistent data
      - PERSISTENCE=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Use a named volume instead of mounting host path directly
      - "localstack_tmp:/tmp/localstack_tmp"
    networks:
      - beauty-booking-local

networks:
  beauty-booking-local:
    driver: bridge

volumes:
  localstack_tmp:
    driver: local